-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.2.7-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             9.4.0.5125
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Dumping database structure for labclase
DROP DATABASE IF EXISTS `POMPONIO`;
CREATE DATABASE IF NOT EXISTS `POMPONIO` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `POMPONIO`;

-- Dumping structure for table POMPONIO.TBL_GUIONISTA
DROP TABLE IF EXISTS `TBL_GUIONISTA`;
CREATE TABLE IF NOT EXISTS `TBL_GUIONISTA` (
  `ID` bigint(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(100) NOT NULL,
  `DIRECCION` varchar(500) NOT NULL,
  `FECHA_NACIMIENTO` date NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `TBL_ACTOR`;
CREATE TABLE IF NOT EXISTS `TBL_ACTOR` (
  `ID` bigint(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(100) NOT NULL,
  `GENERO` varchar(50) NOT NULL,
  `ESTATURA` varchar(10) NOT NULL,
  `COMPLEXION` varchar(50) NOT NULL,
  `COLOR_OJOS` varchar(30) NOT NULL,
  `COLOR_PELO` varchar(30) NOT NULL,
  `FECHA_NACIMIENTO` date NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `TBL_GUION`;
CREATE TABLE IF NOT EXISTS `TBL_GUION` (
  `ID` bigint(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE_OBRA` varchar(100) NOT NULL,
  `GENERO_OBRA` varchar(50) NOT NULL,
  `IDEA_CENTRAL` varchar(500) NOT NULL,
  `ID_GUIONISTA` bigint(11) NOT NULL,
  CONSTRAINT `FK_GUION_GUINISTA`
	FOREIGN KEY (ID_GUIONISTA) REFERENCES TBL_GUIONISTA (ID)
	ON DELETE CASCADE,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=latin1

-- Data exporting was unselected.
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
